name = 'PyLadiesCon theme'
license = 'MIT'
licenselink = 'https://github.com/pyladies/global-conference/themes/pyladies/LICENCE'
description = 'Hugo theme for the PyLadiesCon website'
homepage = 'https://github.com/pyladies/global-conference'
demosite = 'https://conference.pyladies.com'
tags = ['conference']
features = []

[author]
  name = 'PyLadiesCon Organizers'
  homepage = 'https://pyladies.com'
